sequence = "GTGTGTTTAGTCCGCCCACGTGTAATTCGTGCGTAGTGCTTTCTTGGTATCTTCCGTATGTCCCCCGCGTTGCTGTCCTTTGCCTTTGAACGTCCACCTATGCTGTGGGGGAGCTCAACTATGCTTCGTCATATGGTCTGTTCATGCTCATAAAGGGGATCTGTCGCCTAGCATAGGCAATAGCGAGTAGGGCCCTTTATAACGCCCAATTAATGTGGCGCATGCGCTCTGACACGAACATACCGCGAACCCTTCATGGCGCCCTCTTAGACTTATTGGACGAGCCCAACGGGCCGGAAGCGATTCCGAAACGGGAAGGTGGCCAGGCCTGGGTGCATTTCTTTACCTAATACATATCGCGACTCATCGGTCGATAAGGCCTCCGGTTACATCCTGTATCGCCATCAAAGTAACCACGTTGGGGCCTTATAGACGACGAGTCTCTGCGAGGGCCCTAAACTTGTGATAAGGATGAGGTATTAGGTTAAACGCTGATGAGCGTATCCCTAGGGCAAGAAGCCACCAAGCCACCCAATTGCTGTCTGAGTGCACTGACATGACATGTAACGTTCATATAGGCGTAATTCAGTAGGACGTGGCCGGGGGATGGTGGACCGAAGCCTTCTGGAACGCGGATACATTTTATCACTGACCCATCTTCTGTTTCATTCGACCAGCAGCTCCTGACTAATGGTAGGAATATGTTGCTCCTCGGCAGTACTTCCGTGAGGGATCCGCGTCACGCACGGCCCATTAGGGGTCATGCCTTTAGCCAAGAGGATTGGATTCTCACGAGGGCAT"

def ATCG_counter():
	A_counter = 0
	T_counter = 0
	G_counter = 0
	C_counter = 0
	for letter in sequence:
		if letter == "A":
			A_counter += 1
		elif letter == "T":
			T_counter += 1
		elif letter == "G":
			G_counter += 1
		elif letter == "C":
			C_counter += 1
	print(A_counter, T_counter, G_counter, C_counter)

ATCG_counter()