protein = "LRNYCRKGMEAGAARTVYEMHHFSVPTAIPKLCVKNRQLCRGLAYTNGSGWPLKTHQSFWEFWLGNVHDAQSPTENGGIDFYKNEYKFRDHYSMKKYVCMSFPHTMRDCDWGQVMRNAYTPWELFYWISHAHIEIVWRKFMFNACCRWDGSRWVRAPQVAHYTLTNMLHKEAVTQTVNKSASICYITHLVDQFHHQPEIFKWMFYSWQRRTGHEPENLAHNPCHIGTWDGAHKGEPNKVMMWYHYYVSEWFNKDSCQYSDSHNYTTKNEVTCYGMKLTGNYFDCTSTKPFSWIHGDWAEANRHFCNPTNMTENENVDPQIEKSTPQCAGGPCWHRGQTMGHDGCTAQYDTIKYLMVHYTYMVEFGIKVPQFNREYPCLRNTWKIAMQQIMVTLCQADTDVETPGQPCWVSRCIIWLDLTKQYCIFNGFYCNRAQNYCGWQPAMDNRIMWEGEEMGCLVYHAYMPTDESQECLSCWIACYFNGKCKKRVNPLPMFMPLLMQAVDQHLKLTESENRPELPSGAVEGYFRCLCFKGMQCSCCDLVGTFFICTDCCKPPRYPCKQEMCHESRYNMAMWDEREGWNVNRLAHGDMFYLSVHVRQSAIWVLRSGLFHLSEIWGFGGTRFMFQCSTNAAFEDSDYSKNWNALNGTIGRQHIAAMPTWIITTYWWQKIIEILRRKKVSPAYCMQGWGTRGGHYGHEWQKDMIHFRWMRGWEGWHFPQGNGEVEHKSRIAVAQFLGYEAEELWCDGEPKSYPSSCFKKGMTAICEIYLCVMRALSWKDMNGLTRIFARQGQHSLDFSQMAVDGVVTSFPSGQIMSMICCTFWIDMYMDRRKQWAIFRSSCLDGRIRYGPTTMRAAIAGIIWPCYRVILCNCFQKMNKCCPEPIEPIRFHDACNRRKILEMFTHAPQAWYPVKQLPYREGGPDSFIVNLRVIHFWWLDRINLHYHLW"
weight_sum = 0
for letter in protein:
	if letter == "A":
		weight_sum += 71.03711
	if letter == "C":
		weight_sum += 103.00919
	if letter == "D":
		weight_sum += 115.02694
	if letter == "E":
		weight_sum += 129.04259
	if letter == "F":
		weight_sum += 147.06841
	if letter == "G":
		weight_sum += 57.02146
	if letter == "H":
		weight_sum += 137.05891
	if letter == "I":
		weight_sum += 113.08406
	if letter == "K":
		weight_sum += 128.09496
	if letter == "L":
		weight_sum += 113.08406
	if letter == "M":
		weight_sum += 131.04049
	if letter == "N":
		weight_sum += 114.04293
	if letter == "P":
		weight_sum += 97.05276
	if letter == "Q":
		weight_sum += 128.05858
	if letter == "R":
		weight_sum += 156.10111
	if letter == "S":
		weight_sum += 87.03203
	if letter == "T":
		weight_sum += 101.04768
	if letter == "V":
		weight_sum += 99.06841
	if letter == "W":
		weight_sum += 186.07931
	if letter == "Y":
		weight_sum += 163.06333

print(weight_sum.__round__(3))