seq_input = "AAGTGCCTCATGTGTCTCCTGATATTAGTCAAGGGTGCGCAACTCTATGAGACCTAGGGACGGTGAAAAACGTTACCTCTAAGCATAAAGTGCGCCCCTGAGCCGGCGGCTTGCATTACGTGAGGCTGTAATGCTAGTCAATATTGGAAACGGCGGAGGACATTGGAGTATACGTGCTGTGGGAGGCCTACACTGCAGAAATCACAGCTCAGCTATTTCGTCTAGGGGACTCACTTGGGGCTTATATATACACCGCGATCTTCTCTTATCCCGGGAATAGCGCGAGACGACGACGGGTACTTTTGGCTACCTGAATCCTTTACAAGGTCTCAACAGACACCAGTCTCGTGTTATTACATGTGCCTAGTCTCGTTCCGACTTCGTCCCTTTAGGGCATCGGGTCTGAGGAGCTCTAAGCGCTGATAGTCAAATTGGTCTTTGTAACACCGGCTAACACCGTGTTTGCGAATTGCGCTCGGGGTCGTAATCCGAGCTGATCCGTGTTTTGGGGCGGCGTAGGACGGCGGTTGATCCGATGCCCATTTCCTTGTCCGACCGGGCCATTCTTCCGTTCACGGATGCCCTTAAAAGAGTCCGTCTCTTGGAGCCTTTTATCTGGCACCCCAAACCATTAGCGCGCGCGCCAGGCCAAGATGTTGAAAATTCACGGTACCTTAGCTGCAGTCTTCGTTCGCAACCGTACTAGCTTCAGGCACCTCTATTGACTACCGGATTGGTTTGAACGTCGTTCCCAGTCCAACGTGAGGACTAGGGACTCCTGTGCGCAGGGGCACAGTGCGTAACTCTTTACAC"

def comp_seq(seq_input):
	comp_seq = []
	for letter in seq_input:
		if letter == "A":
			comp_seq.append("T")
		elif letter == "T":
			comp_seq.append("A")
		elif letter == "G":
			comp_seq.append("C")
		elif letter == "C":
			comp_seq.append("G")
	comp_seq.reverse()
	c_seq = "".join(comp_seq)
	return c_seq

print(comp_seq())

